apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  annotations:                 
    service.beta.openshift.io/inject-cabundle: "true"
  name: addresspools.metallb.io
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  annotations:                 
    service.beta.openshift.io/inject-cabundle: "true"
  name: bgppeers.metallb.io
